apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 3e966ed4dd654367b6b0fff80622fea0e858c2df
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=configmapcontroller&var-version=2.2.335
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/configmapcontroller
    fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/configmapcontroller
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/configmapcontroller/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.335
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/configmapcontroller
    fabric8.io/scm-tag: fabric8-devops-2.0.1
  labels:
    provider: fabric8
    project: configmapcontroller
    version: 2.2.335
    group: io.fabric8.devops.apps
  name: configmapcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      project: configmapcontroller
      provider: fabric8
      group: io.fabric8.devops.apps
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 3e966ed4dd654367b6b0fff80622fea0e858c2df
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=configmapcontroller&var-version=2.2.335
        fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/configmapcontroller
        fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/configmapcontroller
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/configmapcontroller/src/main/fabric8/icon.png
        fabric8.io/git-branch: release-v2.2.335
        fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/configmapcontroller
        fabric8.io/scm-tag: fabric8-devops-2.0.1
        maven.fabric8.io/source-url: jar:file:/home/jenkins/.mvnrepository/io/fabric8/devops/apps/configmapcontroller/2.2.335/configmapcontroller-2.2.335.jar!/META-INF/fabric8/kubernetes.yml
      labels:
        provider: fabric8
        project: configmapcontroller
        version: 2.2.335
        group: io.fabric8.devops.apps
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: fabric8/configmapcontroller:2.3.7
        name: configmapcontroller
      serviceAccountName: configmapcontroller-demo