apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    provider: fabric8
    project: configmapcontroller-demo
    version: 2.2.335
    group: io.fabric8.devops.apps
  name: configmapcontroller-demo
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: configmapcontroller-demo-role
  # hardcoded namespace
  namespace: test2
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - update
      - patch
      - watch
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - deployments
    verbs:
      - list
      - get
      - update
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: configmapcontroller-demo-role-binding
  namespace: test2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmapcontroller-demo-role
subjects:
  - kind: ServiceAccount
    name: configmapcontroller-demo
    namespace: test2