# one Role gives access to services & ingresses in the same namespace as the exposecontroller is running
# other Role gives access to the services in the default namespace

apiVersion: v1
kind: ServiceAccount
metadata:
  name: exposecontroller-demo
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: exposecontroller-demo-role
  namespace: demo
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - update
      - patch
      - watch
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - delete
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: exposecontroller-demo-role-binding
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: exposecontroller-demo-role
subjects:
  - kind: ServiceAccount
    name: exposecontroller-demo
    namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: exposecontroller-demo-default-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: exposecontroller-demo-default-role-binding
  # This only grants permissions within the "default" namespace.
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: exposecontroller-demo-default-role
subjects:
  - kind: ServiceAccount
    name: exposecontroller-demo
    namespace: demo